name: Tests & style checks
on:
  # Trigger on any PR being opened, or on a merge to master (to update the badge)
  pull_request:
  push:
    branches:
      - master
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Composer Dependencies
        run: |
          composer install -q --no-ansi --no-interaction --no-scripts --no-suggest \
            --no-progress --prefer-dist
      - name: Run tests
        run: composer test
      - name: Check style
        run: composer lint

  build:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ ubuntu-latest ]
        php: [ '5.6', '8.1' ]
    name: PHP ${{ matrix.php }} sample
    steps:
      - uses: actions/checkout@v3
      - name: Setup PHP
        uses: nanasess/setup-php@v3
        with:
          php-version: ${{ matrix.php }}
      - name: Install Composer Dependencies
        run: |
          composer install -q --no-ansi --no-interaction --no-scripts --no-suggest \
            --no-progress --prefer-dist
      - name: Run tests
        run: composer test
