name: Tests & style checks
on:
  # Trigger on any PR being opened, or on a merge to master (to update the badge)
  pull_request:
  push:
    branches:
      - master
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: "ramsey/composer-install@v2"
      - name: Check style
        run: composer lint

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: "ramsey/composer-install@v2"
      - name: Run tests
        run: composer test

  # test-php-latest:
  #   name: Test in PHP 5.6
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: "shivammathur/setup-php@v2"
  #       with:
  #         php-version: "latest"
  #     - uses: "ramsey/composer-install@v2"
  #     - name: Run tests
  #       run: composer test